//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetDB1st_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acquired
    {
        public string Acquired_Id { get; set; }
        public System.DateTime Date_Procured { get; set; }
        public string Warranty { get; set; }
        public string Asset_Description { get; set; }
        public string Asset_ID { get; set; }
    }
}
