//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetDB1st_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Surname { get; set; }
        public string Employee_Unit { get; set; }
        public string Asset_ID { get; set; }
    }
}
